%Doctor.Config{
  exception_moduledoc_required: true,
  failed: false,
  ignore_modules: [
    ~r/^GingkoWeb\.CoreComponents$/,
    ~r/^GingkoWeb\.Layouts$/,
    ~r/^GingkoWeb\.ErrorHTML$/,
    ~r/^GingkoWeb\.ErrorJSON$/,
    ~r/^GingkoWeb\.Gettext$/,
    ~r/^GingkoWeb\.EctoExceptions/,
    ~r/^Plug\.Exception\./,
    ~r/^GingkoWeb\.Api\./,
    ~r/^GingkoWeb\.PageController$/,
    ~r/^GingkoWeb\.Endpoint$/,
    ~r/^GingkoWeb\.Router$/,
    ~r/^GingkoWeb\.Telemetry$/,
    ~r/^GingkoWeb\.SetupLive$/,
    ~r/^GingkoWeb\.ProjectLive\.NodeInspectorComponent$/,
    ~r/^GingkoWeb\.ProjectLive\.GraphViewportComponent$/,
    ~r/^Gingko\.Projects\.(Project|ProjectMemory|Session)$/,
    ~r/^Gingko\.Repo$/,
    ~r/^Gingko\.MCP\.Tools\./,
    ~r/^Gingko\.MCP\.ToolResponse$/
  ],
  ignore_paths: [],
  min_module_doc_coverage: 0,
  min_module_spec_coverage: 0,
  min_overall_doc_coverage: 0,
  min_overall_moduledoc_coverage: 100,
  min_overall_spec_coverage: 0,
  raise: false,
  reporter: Doctor.Reporters.Full,
  struct_type_spec_required: true,
  umbrella: false
}
