defmodule Gingko.Summaries.PrincipalMemorySection do
  @moduledoc """
  Schema for project-level principal memory sections.

  Two kinds:

    * `charter` — user-authored project intent ("constitution"). Untouched by
      the regeneration worker. Honors the `locked` flag for manual pinning.
    * `summary` — LLM-generated synthesis of recent memories, regenerated by
      `Gingko.Summaries.ProjectSummaryWorker`. A `locked=true` summary is
      skipped by the worker.

  One row per (project_key, kind).
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  @kinds ~w(charter summary)

  @type t :: %__MODULE__{}

  schema "principal_memory_sections" do
    field(:project_key, :string)
    field(:kind, :string)
    field(:content, :string, default: "")
    field(:frontmatter, :map, default: %{})
    field(:locked, :boolean, default: false)

    timestamps(type: :utc_datetime)
  end

  @doc "Returns the list of allowed `kind` values."
  def kinds, do: @kinds

  def changeset(section, attrs) do
    section
    |> cast(attrs, [:project_key, :kind, :content, :frontmatter, :locked])
    |> validate_required([:project_key, :kind])
    |> validate_inclusion(:kind, @kinds)
    |> unique_constraint([:project_key, :kind])
  end
end
